#!/bin/bash
mkdir bin
chmod +x *
export MAIN_DIR=$PWD
echo "> Which Server do you want to install?"
echo "Type [1] Java Server"
echo "Type [2] Bedrock Server"

choiceForServer=1
read choiceForServer

# Installing Java 21 JDK

wget -q "https://download.oracle.com/java/21/archive/jdk-21.0.5_linux-aarch64_bin.tar.gz" -O bin/java.tar.xz
cd $MAIN_DIR/bin
echo "> Extracting Java JDK 21 to the bin/ folder. [THIS MAY TAKE SOME TIME]"
tar -xf java.tar.xz && mv "jdk-21.0.5_linux-aarch64_bin" java_bins

cd $MAIN_DIR
echo "> Running Java Installation..."
./installJava

echo "> Installing AFK(Away From Keyboard) Script "
python3 -m pip install bpytop
echo ""
